version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - fetus-hina
  assignees:
  - fetus-hina
  labels:
  - dependencies
  ignore:
  - dependency-name: npm-asset/bootswatch
    versions:
    - "> 3.4.1.pre.patch1"
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.71
    - 0.12.74
    - 0.12.75
    - 0.12.76
    - 0.12.77
    - 0.12.79
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.84
  - dependency-name: jp3cki/uuid
    versions:
    - 1.0.0
  - dependency-name: codeception/codeception
    versions:
    - 4.1.17
    - 4.1.18
    - 4.1.19
    - 4.1.20
  - dependency-name: laminas/laminas-feed
    versions:
    - 2.14.0
    - 2.14.1
  - dependency-name: php-curl-class/php-curl-class
    versions:
    - 8.9.1
    - 8.9.2
    - 9.0.0
  - dependency-name: symfony/yaml
    versions:
    - 5.2.3
    - 5.2.5
  - dependency-name: christian-riesen/base32
    versions:
    - 1.6.0
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.1
  - dependency-name: phpseclib/phpseclib
    versions:
    - 3.0.5
