mapping:
  "AIZAWA Hina <hina@fetus.jp>":
    - "AIZAWA Hina <hina@bouhime.com>"
    - "AIZAWA, Hina <hina@bouhime.com>"

  "Koichi Watanabe <wkoichi@gmail.com>":
    - "Unknown <wkoichi@gmail.com>"

copy-left:
  "clovervidia <clovervidia@gmail.com>":
    - "messages/en-GB/weapon-short.php"
    - "messages/en/weapon-short.php"

  "Gosin <canling0@gmail.com>":
    - "messages/zh-TW/ability.php"
    - "messages/zh-TW/ability2.php"
    - "messages/zh-TW/alert.php"
    - "messages/zh-TW/apidoc1.php"
